In [9]:
%config IPCompleter.greedy=True

In [2]:
import numpy as np

data = [(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
        (11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
        (21, 22, 23, 24, 25, 26, 27, 28, 29, 30)]

np_data = np.array(data, dtype=int)
print(np_data)
print("mean: " + str(np.mean(np_data)))
np.savetxt("np_array.csv", np_data, delimiter=",")
# ------------------------------------------------------------------------------------------------------ #

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
mean: 15.5


In [11]:
# (.dim) returns dimensions of a given array.
# below np_data.ndim will return dimensions of np_data (a numpy array)
print("\"np_data is a " + str(np_data.ndim) + "-dimension array\"")
# ------------------------------------------------------------------------------------------------------ #

# (.shape) returns rows and columns of given numpy array
print("\"rows and columns of np_data are " + str(np_data.shape) + " respectively\"")
# ------------------------------------------------------------------------------------------------------ #

# (.itemsize) returns memory-byte-size of each element in numpy array
print("\"memory-size of each item/element in np_data is " + str(np_data.itemsize) + " byte\"")
# ------------------------------------------------------------------------------------------------------ #

# (.dtype) returns data type of numpy array
print("\"data type of numpy array is " + str(np_data.dtype) + "\"")

"np_data is a 2-dimension array"
"rows and columns of np_data are (3, 10) respectively"
"memory-size of each item/element in np_data is 4 byte"
"data type of numpy array is int32"


In [3]:
## numpy operations
# following will assign 10 values equally spaced between 1 and 3
values = np.linspace(1, 5, 5)
print(values) # print above values

[1. 2. 3. 4. 5.]


In [13]:
sumOfColumns = np_data.sum(axis=0) # find sum of each column
meanOfColumns = np.mean(np_data, axis=0, dtype=int) # find mean of each column
mean_meanOfColumns = np.mean(meanOfColumns)

print(np_data)
print()
print("sum of columns = " + str(sumOfColumns)) # print sum of each column
print("mean of columns= " + str(meanOfColumns)) # print mean of each column
print(sum(meanOfColumns), mean_meanOfColumns)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

sum of columns = [33 36 39 42 45 48 51 54 57 60]
mean of columns= [11 12 13 14 15 16 17 18 19 20]
155 15.5


In [14]:
sumOfRows = np_data.sum(axis=1) # find sum of each row
meanOfRows = np.mean(np_data, axis=1) # find mean of each row
mean_meanOfRows = np.mean(meanOfRows)

print(np_data)
print()
print("sum of each row = " + str(sumOfRows)) # print sum of each row
print("mean of each row= " + str(meanOfRows)) # print mean of each row
print(sum(sumOfRows), mean_meanOfRows)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

sum of each row = [ 55 155 255]
mean of each row= [ 5.5 15.5 25.5]
465 15.5


In [15]:
sqrtOf_np_data = np.sqrt(np_data)
print(sqrtOf_np_data)

[[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
  2.64575131 2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
  4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
  5.19615242 5.29150262 5.38516481 5.47722558]]


In [16]:
standardDeviation = np.std(np_data)
print(standardDeviation)

8.65544144839919


In [5]:
### arithmatic operations
# addition: adds each element for numeric array
# addition: concatinates each element for strin array

print(np_data*3) # multiplies each element wi
print(str(np_data)*3)

[[ 3  6  9 12 15 18 21 24 27 30]
 [33 36 39 42 45 48 51 54 57 60]
 [63 66 69 72 75 78 81 84 87 90]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]][[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]][[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
